# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy WebApi

on:
  push:
    branches: [ "main" ]

jobs:
  Deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: setup-msbuild       
      uses: microsoft/setup-msbuild@v1

    - name: print working directory
      run: pwd

    - name: print directory contents
      run: dir
      
    - name: Restore dependencies
      run: dotnet restore landscape-architecture.WebAPI/landscape-architecture.WebAPI.csproj

      
    - name: Build
      run: msbuild landscape-architecture.WebAPI/ /p:Configuration=Debug

    - name: Publish
      run: dotnet publish landscape-architecture.WebAPI/landscape-architecture.WebAPI.csproj -c Debug

    - name: Stop landscape-architecture-WebAPI.service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl stop landscape-architecture-WebAPI
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy to Server via SCP
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        local: /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/bin/Debug/net7.0/publish/
        remote: /home/qmiller/
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      env:
        ASPNETCORE_ENVIRONMENT: Development

    - name: Copy Conversion Scripts to Server via SCP (1/4)
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        local: /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.dll
        remote: /home/qmiller/ConversionScripts.dll
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy Conversion Scripts to Server via SCP (2/4)
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        local: /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.exp
          - /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.lib 
          - /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.pdb
        remote: /home/qmiller/ConversionScripts.exp
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy Conversion Scripts to Server via SCP (3/4)
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        local: /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.lib
          - /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.pdb
        remote: /home/qmiller/ConversionScripts.pdb
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy Conversion Scripts to Server via SCP (4/4)
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        local: /home/runner/work/landscape-AR/landscape-AR/landscape-architecture.WebAPI/landscape-architecture.WebAPI/ConversionScripts.pdb
        remote: /home/qmiller/ConversionScripts.pdb
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy files on Server to deploy directory
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo cp -r /home/qmiller/* /var/www/LAAR-WebApi.dxgdev.info/
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Start landscape-architecture-WebAPI.service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl start landscape-architecture-WebAPI
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
